"""update_payment_status_enum

Revision ID: 0005
Revises: 0004
Create Date: 2026-02-27 13:56:37.213858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookings_payment_id'), 'bookings', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_bookings_payment_id'), 'bookings', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###